blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.entrance, name='entrance'),
    path('index/', views.index, name='index'),
    path('posts/<int:pk>/', views.detail, name='detail'),
    path('archives/<int:year>/<int:month>/', views.archive, name='archive'),
    path('categories/<int:pk>/', views.category, name='category'),
    path('tags/<int:pk>/', views.tag, name='tag'),
    path('timelines/', views.timelines, name='timelines'),
    path('about/', views.about, name='about'),
]

comments/urls.py
from django.urls import path

from comments import views

app_name = 'comments'

urlpatterns = [
    path('comment/<int:post_pk>', views.comment, name='comment'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('comments.urls')),
]

blog/models.py
import markdown
from django.contrib.auth.models import User
from django.db import models

from django.urls import reverse
from django.utils import timezone
from django.utils.html import strip_tags


class Category(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name


class Tag(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name


class Post(models.Model):
    title = models.CharField('标题', max_length=68)
    body = models.TextField('正文')
    created_time = models.DateTimeField('创建时间', default=timezone.now)
    modified_time = models.DateTimeField('修改时间')
    excerpt = models.CharField('摘要', max_length=256, blank=True)
    category = models.ForeignKey(Category, verbose_name='分类', on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, verbose_name='标签', blank=True)
    author = models.ForeignKey(User, verbose_name='作者', on_delete=True)
    views = models.PositiveIntegerField(default=0, editable=False)

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.modified_time = timezone.now()
        # md = markdown.Markdown(extensions=[
        #     'markdown.extensions.extra',
        #     'markdown.extensions.codehilite',
        # ])
        # self.excerpt = strip_tags(md.convert(self.body))[:54]
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-created_time']

comments/models.py
from django.db import models
from django.utils import timezone


class Comment(models.Model):
    name = models.CharField('名字', max_length=64)
    email = models.EmailField('邮箱')
    url = models.URLField('网址', blank=True)
    text = models.TextField('内容')
    created_time = models.DateTimeField('创建时间', default=timezone.now)
    post = models.ForeignKey('blog.Post', verbose_name='文章', on_delete=models.CASCADE)

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name
        ordering = ['-created_time']

    def __str__(self):
        return '{}: {}'.format(self.name, self.text[:20])

comments/forms.py
from django import forms

from comments.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'url', 'text']

blog/views.py
import re

import markdown
from markdown.extensions.toc import TocExtension
from django.utils.text import slugify
from django.shortcuts import render, get_object_or_404

from blog.models import Post, Category, Tag


def entrance(request):
    return render(request, 'entrance.html')


def index(request):
    post_list = Post.objects.all()
    return render(request, 'blog/index.html', context={'post_list': post_list})


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.increase_views()
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        TocExtension(slugify=slugify),
    ])
    post.body = md.convert(post.body)
    m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
    post.toc = m.group(1) if m is not None else ''
    return render(request, 'blog/detail.html', context={'post': post})


def archive(request, year, month):
    post_list = Post.objects.filter(created_time__year=year,
                                    created_time__month=month
                                    ).order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})


def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate)
    return render(request, 'blog/index.html', context={'post_list': post_list})


def tag(request, pk):
    t = get_object_or_404(Tag, pk=pk)
    post_list = Post.objects.filter(tags=t)
    return render(request, 'blog/index.html', context={'post_list': post_list})


def timelines(request):
    return render(request, 'blog/timelines.html')


def about(request):
    return render(request, 'blog/about.html')

comments/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST

from blog.models import Post
from comments.forms import CommentForm


@require_POST
def comment(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)

    form = CommentForm(request.POST)

    if form.is_valid():
        # commit=False 的作用是仅仅利用表单的数据生成 Comment 模型类的实例，但还不保存评论数据到数据库。
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
        messages.add_message(request, messages.SUCCESS, '评论发表成功！', extra_tags='success')
        return redirect(post)

    context = {
        'post': post,
        'form': form,
    }
    messages.add_message(request, messages.ERROR, '评论发表失败！请修改表单中的错误后重新提交。', extra_tags='danger')
    return render(request, 'comments/preview.html', context=context)

templates/base.html
{% load static %}
{% load blog_extras %}
<!DOCTYPE html>
<html>
<head>
    <title>Super 5 的博客</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" href="{% static 'blog/img/favicon.ico' %}">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'blog/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">

    <link href="https://cdn.bootcss.com/highlight.js/9.15.8/styles/github.min.css" rel="stylesheet">

    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>

    <style>
        .codehilite {
            padding: 0;
        }

        /* for block of numbers */
        .hljs-ln-numbers {
            -webkit-touch-callout: none;
            -webkit-user-select: none;
            -khtml-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;

            text-align: center;
            color: #ccc;
            border-right: 1px solid #CCC;
            vertical-align: top;
            padding-right: 5px;
        }

        .hljs-ln-n {
            width: 30px;
        }

        /* for block of code */
        .hljs-ln .hljs-ln-code {
            padding-left: 10px;
            white-space: pre;
        }
    </style>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-12">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>Super 5</b></a></h1>
                    <p class="description">
                        <span class="ion-android-favorite">
                            你一笑风来 你再笑花开 北方雨水充足 我醒来的时候 你一言不发的还在
                        </span>
                        </p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <nav class="main-nav" role="navigation">
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:timelines' %}" data-hover="归档">归档</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:about' %}" data-hover="关于">关于</a></li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </header>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-9 main-content">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-3">
                {% block toc %}
                {% endblock toc %}

                {% show_recent_posts %}
                {% show_archives %}
                {% show_categories %}
                {% show_tags %}

                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
            <div class="actGotop"><a href="javascript:;" title="返回顶部">
                <span class="ion-jet"></span>
            </a></div>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2021 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                </p>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'blog/js/script.js' %}"></script>
<script src="{% static 'blog/js/gotop.js' %}"></script>

<script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
<script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
<script>
    hljs.initHighlightingOnLoad();
    hljs.initLineNumbersOnLoad();
</script>

</body>
</html>

templates/base2.html
{% load static %}
{% load blog_extras %}
<!DOCTYPE html>
<html>
<head>
    <title>Super 5 的博客</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" href="{% static 'blog/img/favicon.ico' %}">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'blog/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/timelines.css' %}">

    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-12">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>Super 5</b></a></h1>
                    <p class="description">
                        <span class="ion-android-favorite">
                            你一笑风来 你再笑花开 北方雨水充足 我醒来的时候 你一言不发的还在
                        </span>
                        </p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <nav class="main-nav" role="navigation">
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:timelines' %}" data-hover="归档">归档</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:about' %}" data-hover="关于">关于</a></li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </header>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-12">
                {% block main %}
                {% endblock main %}
            </main>
            <div class="actGotop"><a href="javascript:;" title="返回顶部">
                <span class="ion-jet"></span>
            </a></div>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2021 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                </p>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'blog/js/script.js' %}"></script>
<script src="{% static 'blog/js/gotop.js' %}"></script>

<script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
<script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
<script>
    hljs.initHighlightingOnLoad();
    hljs.initLineNumbersOnLoad();
</script>

</body>
</html>

templates/blog/about.html
{% extends 'base2.html' %}
{% load static %}
{% block main %}
    <div class="content-body">
        <div class="container">
            <div class="row">
                <main class="col-md-12">
                    <h1 class="page-title">About Me</h1>
                    <article class="post">
                        <div class="entry-content clearfix">
                            <figure class="img-responsive-center">
                                <img class="img-responsive" src="{% static 'blog/img/me.jpg' %}" alt="Developer Image" style="width: 50%">
                            </figure>
                            <p>This is 吧啦吧啦吧啦吧啦吧啦吧啦 一大段.</p>
                            <div class="height-40px"></div>
                            <h2 class="title text-center">Social</h2>
                            <ul class="social">
                                <li><a href="#"><span class="ion-social-github"></span></a></li>
                                <li><a href="#"><span class="ion-chatbubbles"></span></a></li>
                                <li><a href="#"><span class="ion-social-googleplus"></span></a></li>
                                <li><a href="#"><span class="ion-social-whatsapp"></span></a></li>
                            </ul>
                        </div>
                    </article>
                </main>
            </div>
        </div>
    </div>
{% endblock %}

templates/blog/detail.html
{% extends 'base.html' %}
{% load comments_extras %}

{% block main %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.count }} 评论</a></span>
                <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body|safe }}
        </div>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        {% show_comment_form post %}
        <div class="comment-list-panel">
            {% show_comments post %}
        </div>
    </section>
{% endblock %}

{% block toc %}
    {% if post.toc %}
        <div class="widget widget-content">
            <h3 class="widget-title">文章目录</h3>
            <div class="toc">
                <ul>
                    {{ post.toc|safe }}
                </ul>
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/blog/inclusions/_archives.html
<div class="widget widget-archives">
    <h3 class="widget-title">归档</h3>
    <ul>
        {% for date in date_list %}
            <li>
                <a href="{% url 'blog:archive' date.year date.month %}">
                    {{ date.year }} 年 {{ date.month }} 月
                </a>
            </li>
        {% empty %}
            暂无归档！
        {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_categories.html
<div class="widget widget-category">
    <h3 class="widget-title">分类</h3>
    <ul>
        {% for category in category_list %}
            <li>
                <a href="{% url 'blog:category' category.pk %}">{{ category.name }}</a>
            </li>
        {% empty %}
            暂无分类！
        {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_recent_posts.html
<div class="widget widget-recent-posts">
  <h3 class="widget-title">最新文章</h3>
  <ul>
    {% for post in recent_post_list %}
      <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      </li>
    {% empty %}
      暂无文章！
    {% endfor %}
  </ul>
</div>

templates/blog/inclusions/_tags.html
<div class="widget widget-tag-cloud">
  <h3 class="widget-title">标签</h3>
  <ul>
    {% for tag in tag_list %}
      <li>
        <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
      </li>
    {% empty %}
      暂无标签！
    {% endfor %}
  </ul>
</div>

templates/blog/index.html
{% extends 'base.html' %}

{% block main %}
    {% for post in post_list %}
        <article class="post post-{{ post.pk }}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-date">
                        <a href="#"><time class="entry-date"
                        datetime="{{ post.created_time }}">{{ post.created_time }}</time>
                    </a></span>
                    <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                    
                    <span class="comments-link"><a href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.count }} 评论</a></span>
                    <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.excerpt }}...</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}
    
{% endblock %}

templates/blog/timelines.html
{% extends 'base2.html' %}

{% block main %}
<ul class="timeLine" style="width: 1200px;">
    <li>
        <div class="con">css时间轴 - 样式</div>
    </li>
    <li>
        <div class="con">css时间轴 - 样式</div>
    </li>
    <li>
        <div class="con">css时间轴 - 样式</div>
    </li>
    <li>
        <div class="con">css时间轴 - 样式</div>
    </li>
    <li>
        <div class="con">css时间轴 - 样式</div>
    </li>
    <li>
        <div class="con">css时间轴 - 样式</div>
    </li>
    <li class="on">
        <div class="con">css时间轴 - 样式内容能容纳</div>
    </li>
    <li>
        <div class="con">css时间轴 - 样式</div>
    </li>
    <li>
        <div class="con">css时间轴 - 样式</div>
    </li>
    <li>
        <div class="con">流程结束</div>
    </li>
</ul>
{% endblock %}

templates/comments/inclusions/_form.html
<form action="{% url 'comments:comment' post.pk %}" method="post" class="comment-form">
  {% csrf_token %}
  <div class="row">
    <div class="col-md-4">
      <label for="{{ form.name.id_for_label }}">{{ form.name.label }}：</label>
      {{ form.name }}
      {{ form.name.errors }}
    </div>
    <div class="col-md-4">
      <label for="{{ form.email.id_for_label }}">{{ form.email.label }}：</label>
      {{ form.email }}
      {{ form.email.errors }}
    </div>
    <div class="col-md-4">
      <label for="{{ form.url.id_for_label }}">{{ form.url.label }}：</label>
      {{ form.url }}
      {{ form.url.errors }}
    </div>
    <div class="col-md-12">
      <label for="{{ form.text.id_for_label }}">{{ form.text.label }}：</label>
      {{ form.text }}
      {{ form.text.errors }}
      <button type="submit" class="comment-btn">发表</button>
    </div>
  </div>
</form>

templates/comments/inclusions/_list.html
<h3>评论列表，共 <span>{{ comment_count }}</span> 条评论</h3>
<ul class="comment-list list-unstyled">
  {% for comment in comment_list %}
    <li class="comment-item">
      <span class="nickname">{{ comment.name }}</span>
      <time class="submit-date" datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
      <div class="text">
        {{ comment.text|linebreaks }}
      </div>
    </li>
  {% empty %}
    暂无评论
  {% endfor %}
</ul>

templates/comments/preview.html
{% extends 'base.html' %}
{% load comments_extras %}

{% block main %}
  {% show_comment_form post form %}
{% endblock main %}

templates/entrance.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Super 5</title>
    <style>
        html {
            width: 100%;
            height: 100%;
        }
        body {
            background-repeat: no-repeat;
            background-position: center center #2D0F0F;
            background-color: #00BDDC;
            background-image: url({% static 'blog/img/c.jpg' %});
            background-size: 100% 100%;
        }
        .snow-container {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            {#pointer-events: none;#}
            z-index: 100001;
            cursor: pointer;
        }
    </style>
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/snow.js' %}"></script>
</head>
<body>
<a href="{% url 'blog:index' %}">
    <div class="snow-container"></div>
</a>
</body>
</html>